apiVersion: v1
kind: Service
metadata:
  name: rpi4-service-temp
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi4-temperature
spec:
  clusterIP: None   #most relevant setting -> https://github.com/k3s-io/k3s/discussions/9726
  ports:
    - name: http
      protocol: TCP
      port: 9101
      targetPort: 9101