apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: rpi4-service-temp-1 # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  namespace: {{ .Release.Namespace }}
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: rpi4-service-temp
addressType: IPv4
ports:
  - name: http # should match with the name of the service port defined above
    appProtocol: http
    protocol: TCP
    port: 9101
endpoints:
  - addresses:
      - "192.168.1.100"