apiVersion: v1
kind: Service
metadata:
  name: rpi4-service-temp
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi4-temperature
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9101
      targetPort: 9101