apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airquality.fullname" . }}
  namespace: {{ .Values.appNamespace }}
  labels:
    {{- include "airquality.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "airquality.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      #{{- with .Values.podAnnotations }}
      #annotations:
      #  {{- toYaml . | nindent 8 }}
      #{{- end }}
      labels:
        {{- include "airquality.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
          - name: AIRQUALITY_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: token

          - name: CONFIGPATH
            value: "/etc/config/appconfig.yaml"

          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
            readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.config.configmapName }}
          items:
          - key: appconfig.yaml
            path: appconfig.yaml
