apiVersion: v1
kind: Service
metadata:
  name: {{ include "airquality.fullname" . }}
  labels:
    {{- include "airquality.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }} #http
      protocol: TCP
      name: http
  selector:
    {{- include "airquality.selectorLabels" . | nindent 4 }}
