apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airquality
  namespace: argocd
spec:
  destination:
    namespace: airquality
    server: https://kubernetes.default.svc
  project: default
  sources:
  - ref: valuesrepo
    repoURL: https://github.com/HomeProjectSandbox/basicsetup_kubernetes_config.git
    targetRevision: main
  - helm:
      valueFiles:
      - $valuesrepo/argoenv/airquality/values.yaml
    path: kubernetes/airquality/airquality
    repoURL: https://github.com/HomeProjectSandbox/basicsetup_kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
